# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://miklevin.github.io/OhAwf/"

git_url = "https://github.com/miklevin/OhAwf/tree/{branch}/"

def custom_doc_links(name): return None
