# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['OhAwf']

# Cell
"""
Google OAuth2 login module.
"""
import json
import pickle
from urllib.request import urlopen
import google.auth.transport.requests
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow


class OhAwf:
    """Login to Google services."""

    def __init__(self):
        self.url = "https://www.googleapis.com/oauth2/v1/tokeninfo?access_token="
        self.scopes = ["https://www.googleapis.com/auth/webmasters.readonly"]
        self.credentials = None
        with open("credentials.json", "rb") as handle:
            self.credentials = json.load(handle)
        self.run()

    def login(self):
        """Start web-based Google OAuth2 login prompt."""
        flow = InstalledAppFlow.from_client_config(self.credentials, self.scopes)
        self.credentials = flow.run_console()
        with open("credentials.pkl", "wb") as handle:
            pickle.dump(self.credentials, handle)
        return self.credentials

    def refresh_token(self):
        """Refresh token to make new logins generally not required."""
        with open("credentials.pkl", "rb") as handle:
            self.credentials = pickle.load(handle)
        cred_url = self.url + self.credentials.token
        try:
            cred_response = urlopen(cred_url)
        except:
            request = google.auth.transport.requests.Request()
            self.credentials.refresh(request)
            with open("credentials.pkl", "wb") as handle:
                pickle.dump(self.credentials, handle)
        return self.credentials

    def run(self):
        try:
            self.credentials = self.refresh_token()
        except:
            self.credentials = self.login()
        return self.credentials

if __name__ == "__main__":
    owauf = OhAwf()
    credentials = owauf.run()
    print(credentials)